const ports = [
  ['Europe', 'Rotterdam, NL'], ['Europe', 'Antwerp-Bruges, BE'], ['Europe', 'Hamburg, DE'], ['Europe', 'Felixstowe, GB'], ['Europe', 'Piraeus, GR'],
  ['Asia', 'Shanghai, CN'], ['Asia', 'Ningbo-Zhoushan, CN'], ['Asia', 'Yantian, CN'], ['Asia', 'Singapore, SG'], ['Asia', 'Busan, KR'], ['Asia', 'Hong Kong, HK'], ['Asia', 'Jebel Ali, AE'], ['Asia', 'Mumbai (Nhava Sheva), IN'],
  ['Africa', 'Tanger Med, MA'], ['Africa', 'Durban, ZA'], ['Africa', 'Mombasa, KE'], ['Africa', 'Lagos (Apapa), NG'],
  ['North America', 'Los Angeles / Long Beach, US'], ['North America', 'New York / New Jersey, US'], ['North America', 'Savannah, US'], ['North America', 'Houston, US'], ['North America', 'Vancouver, CA'], ['North America', 'Manzanillo, MX'],
  ['South America', 'Santos, BR'], ['South America', 'Buenos Aires, AR'], ['South America', 'Cartagena, CO'], ['South America', 'Callao, PE'], ['South America', 'Valparaíso, CL'],
  ['Oceania', 'Sydney, AU'], ['Oceania', 'Melbourne, AU'], ['Oceania', 'Brisbane, AU'], ['Oceania', 'Auckland, NZ']
];
const profiles = { 'Europe-Asia':[28,38,2500,4100], 'Europe-Africa':[14,25,1800,3100], 'Europe-North America':[11,20,1700,2900], 'Europe-South America':[18,29,2100,3400], 'Europe-Oceania':[38,50,3500,5300], 'Asia-Africa':[19,31,2200,3600], 'Asia-North America':[14,26,2100,3800], 'Asia-South America':[30,44,3000,4800], 'Asia-Oceania':[12,22,1800,3000], 'Africa-North America':[25,37,2700,4200], 'Africa-South America':[17,29,2300,3600], 'Africa-Oceania':[28,42,3200,5000], 'North America-South America':[14,27,1900,3300], 'North America-Oceania':[24,38,3000,4700], 'South America-Oceania':[30,45,3400,5200] };
const $ = id => document.getElementById(id);
const form = $('heroQuoteForm');
const money = amount => new Intl.NumberFormat('en-GB', { style: 'currency', currency: 'EUR', maximumFractionDigits: 0 }).format(amount);
const continentFor = port => ports.find(([, name]) => name === port)?.[0];
function populate(select) { let current = ''; ports.forEach(([continent, name]) => { if (continent !== current) { current = continent; const group = document.createElement('optgroup'); group.label = continent; select.append(group); } const option = document.createElement('option'); option.value = name; option.textContent = name; select.lastElementChild.append(option); }); }
function routeEstimate() { const origin = $('heroOrigin').value, destination = $('heroDestination').value, equipment = $('heroContainer').value; if (!origin || !destination || origin === destination) return null; const from = continentFor(origin), to = continentFor(destination); const key = [from, to].sort().join('-'); let [daysLow, daysHigh, low, high] = profiles[key] || [5,11,900,1600]; if (from === to) { [daysLow, daysHigh, low, high] = from === 'Europe' ? [4,10,750,1350] : [6,15,1050,1900]; } const multiplier = equipment.includes('Reefer') ? 1.3 : equipment.includes('High Cube') ? 1.08 : equipment.includes("20'") ? .78 : 1; return { daysLow, daysHigh, low: Math.round(low * multiplier / 50) * 50, high: Math.round(high * multiplier / 50) * 50 }; }
function update() { const estimate = routeEstimate(), result = $('heroQuoteResult'); if (!estimate) { result.innerHTML = '<span>Select two different ports for a planning estimate.</span>'; return; } result.innerHTML = `<div><span>Ocean transit</span><b>${estimate.daysLow}–${estimate.daysHigh} days</b></div><div><span>Port-to-port estimate</span><b>${money(estimate.low)}–${money(estimate.high)}</b></div>`; }
populate($('heroOrigin')); populate($('heroDestination'));
['heroOrigin', 'heroDestination', 'heroContainer'].forEach(id => $(id).addEventListener('change', update));
form.addEventListener('submit', async event => { event.preventDefault(); const estimate = routeEstimate(); const status = $('heroQuoteStatus'); if (!estimate) { status.textContent = 'Please choose two different ports first.'; return; } const data = new FormData(form); const payload = { name: data.get('Contact name'), email: data.get('Email'), company: data.get('Company'), details: { origin: data.get('Origin'), destination: data.get('Destination'), container: data.get('Container'), planningEstimate: `${estimate.daysLow}–${estimate.daysHigh} days; ${money(estimate.low)}–${money(estimate.high)}` } }; status.textContent = 'Sending your request…'; try { const response = await fetch(`${window.LEAD_AGENT_URL || 'http://localhost:8787'}/api/quote`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) }); if (!response.ok) throw new Error('Request failed'); status.textContent = 'Thank you — your estimate has been emailed to our team.'; } catch { status.innerHTML = 'We could not send this request right now. Please email <a href="mailto:pr@sea-and-shore.com">pr@sea-and-shore.com</a>.'; } });
