const translations = {
  nl: {
    'Services':'Diensten', 'Insights':'Kennisbank', 'News':'Nieuws', 'Contact':'Contact', 'Request a quote →':'Offerte aanvragen →', 'Request a quote':'Offerte aanvragen', 'Quote':'Offerte', 'Home':'Home',
    'Plan your shipment →':'Plan uw zending →', 'Talk to the team →':'Neem contact op →', 'Explore':'Ontdek', 'Partners':'Partners', 'Privacy statement':'Privacyverklaring', 'Privacy & cookies':'Privacy & cookies',
    'Sea freight update':'Zeevrachtupdate', 'All news →':'Alle nieuws →', 'International container news':'Internationaal containernieuws',
    'Rotterdam · Global reach · 24/7':'Rotterdam · Wereldwijd bereik · 24/7', 'One partner. Every step.':'Eén partner. Elke stap.', 'What we do':'Wat we doen', 'The Sea and Shore way':'De Sea and Shore-aanpak',
    'Sea freight':'Zeevracht', 'Air, road & rail':'Lucht, weg & spoor', 'Special cargo':'Speciale lading', 'Customs clearance':'Douaneafhandeling', 'Documentation':'Documentatie', 'Warehousing':'Opslag',
    'Answers before you need them.':'Antwoorden vóór u ze nodig hebt.', 'Basics':'Basis', 'Volume':'Volume', 'Cost':'Kosten', 'Read →':'Lees →', 'Open the knowledge area →':'Open de kennisbank →',
    'Regular contact':'Regulier contact', 'Urgent service':'Spoedservice', 'Our Rotterdam office':'Ons kantoor in Rotterdam', 'Available 24/7':'24/7 bereikbaar', 'Company video':'Bedrijfsvideo', 'See how we work.':'Zie hoe we werken.',
    'Quote planner':'Offerteplanner', 'Shipment details':'Zendinggegevens', 'Planning estimate':'Planningsinschatting', 'Send quote request →':'Offerteaanvraag versturen →',
    'Instant route planner':'Directe routeplanner', 'Plan your route.':'Plan uw route.', 'From':'Van', 'To':'Naar', 'Container':'Container', 'Work email':'Zakelijk e-mailadres', 'Name':'Naam', 'Email this estimate →':'Stuur deze inschatting →',
    'Your shipment plan':'Uw zendingplan', 'Ocean transit':'Transittijd over zee', 'Port-to-port estimate':'Haven-tot-haven-inschatting', 'Select a port':'Kies een haven', 'Select two different ports for a planning estimate.':'Kies twee verschillende havens voor een planningsinschatting.',
    'FCL':'FCL', 'Latest developments from Sea and Shore.':'Laatste ontwikkelingen van Sea and Shore.', 'Knowledge for clearer decisions.':'Kennis voor heldere beslissingen.',
    'Supply chain, made clear.':'Logistiek, helder geregeld.', 'Based in Rotterdam':'Gevestigd in Rotterdam', 'Connected worldwide':'Wereldwijd verbonden',
    'International logistics works best when one team owns the whole picture.':'Internationale logistiek werkt het best wanneer één team het volledige overzicht heeft.',
    'Sea and Shore combines freight forwarding, customs and warehousing into one dependable operation.':'Sea and Shore combineert expeditie, douane en opslag in één betrouwbare operatie.',
    'From Rotterdam, we work with trusted partners in more than 120 countries and keep you informed from booking to final delivery.':'Vanuit Rotterdam werken wij met betrouwbare partners in meer dan 120 landen en houden wij u op de hoogte van boeking tot eindlevering.',
    'Control, not complexity':'Controle, geen complexiteit', 'A better view of every moving part.':'Beter zicht op elk bewegend onderdeel.',
    'One team connects planning, documentation and transport execution.':'Eén team verbindt planning, documentatie en transportuitvoering.',
    'Reliable handovers.':'Betrouwbare overdrachten.', 'Fast action':'Snel handelen', 'Urgent question? We are available 24/7.':'Spoedvraag? Wij zijn 24/7 bereikbaar.', 'Contact operations →':'Neem contact op met operations →',
    'Customs support that keeps cargo moving.':'Douaneondersteuning die uw lading in beweging houdt.', 'Practical expertise for imports, documents and compliance.':'Praktische expertise voor import, documenten en compliance.',
    'Logistics that moves business.':'Logistiek die uw bedrijf vooruithelpt.', 'Start with the service you need.':'Begin met de dienst die u nodig heeft.',
    'We coordinate the connected steps, so your team keeps one clear line of communication.':'Wij coördineren alle verbonden stappen, zodat uw team één duidelijke communicatielijn houdt.',
    'FCL and LCL on the main trade lanes, with space confirmed before the cut-off.':'FCL en LCL op de belangrijkste handelsroutes, met ruimte bevestigd vóór de cut-off.', 'Explore sea freight →':'Ontdek zeevracht →',
    'Faster routings for when the sailing schedule no longer fits the deadline.':'Snellere routes wanneer het vaarschema niet meer binnen uw deadline past.', 'Explore transport modes →':'Ontdek transportmodaliteiten →',
    'Out-of-gauge, reefer and dangerous goods, planned around permits and equipment.':'Out-of-gauge-, reefer- en gevaarlijke goederen, gepland rond vergunningen en materieel.', 'Explore special cargo →':'Ontdek speciale lading →',
    'AEO-certified import, export and transit entries, checked before submission.':'AEO-gecertificeerde import-, export- en transitaangiften, gecontroleerd vóór indiening.', 'Explore customs support →':'Ontdek douaneondersteuning →',
    'Bills of lading, origin certificates and credit document sets, checked against the booking.':'Cognossementen, oorsprongscertificaten en kredietdocumenten, gecontroleerd aan de hand van de boeking.', 'Explore documentation →':'Ontdek documentatie →',
    'Bonded and standard storage near the port, connected to the same booking.':'Douane-entrepot en reguliere opslag nabij de haven, gekoppeld aan dezelfde boeking.', 'Explore warehousing →':'Ontdek opslag →',
    'See all services, including insurance and tracking →':'Bekijk alle diensten, inclusief verzekering en tracking →',
    'A practical knowledge area for importers, written by the people who handle the shipments.':'Een praktische kennisbank voor importeurs, geschreven door de mensen die de zendingen behandelen.',
    'How a container shipment actually runs.':'Hoe een containerzending werkelijk verloopt.', 'The sequence from booking to delivery, and which container fits which cargo.':'De stappen van boeking tot levering en welke container bij welke lading past.',
    'FCL or LCL: which one fits your cargo.':'FCL of LCL: welke past bij uw lading?', 'Where the tipping point sits, and what changes at the destination when you share a box.':'Waar het omslagpunt ligt en wat er op bestemming verandert wanneer u een container deelt.',
    'What actually drives your freight rate.':'Wat uw vrachttarief werkelijk bepaalt.', 'Why the lowest quote is often not the lowest cost, and which charges arrive later.':'Waarom de laagste offerte vaak niet de laagste kosten geeft en welke kosten later komen.',
    'Personal service, backed by a global network.':'Persoonlijke service, ondersteund door een wereldwijd netwerk.', 'countries reached through trusted local partners':'landen bereikt via betrouwbare lokale partners', 'availability for urgent logistics questions':'bereikbaar voor urgente logistieke vragen', 'certified, with fast-track import support':'gecertificeerd, met versnelde importondersteuning', 'point of contact across your logistics process':'aanspreekpunt voor uw volledige logistieke proces',
    'Choose a topic':'Kies een onderwerp', 'New quote or shipment':'Nieuwe offerte of zending', 'Existing shipment or booking':'Bestaande zending of boeking', 'Customs or documentation':'Douane of documentatie', 'Warehousing or distribution':'Opslag of distributie', 'Partnership or general question':'Samenwerking of algemene vraag', 'Other':'Anders', 'Send a message':'Stuur een bericht', 'Tell us what you need. We will route it to the right team.':'Vertel ons wat u nodig heeft. Wij sturen uw vraag naar het juiste team.', 'Company':'Bedrijf', 'Phone':'Telefoon', 'What do you need help with?':'Waarmee kunnen wij helpen?', 'How can we help?':'Hoe kunnen wij helpen?', 'Send message →':'Bericht versturen →',
    'Full container load (FCL)':'Volle containerlading (FCL)', 'Less than container load (LCL)':'Deellading (LCL)', 'Air freight':'Luchtvracht', 'Road or rail freight':'Weg- of spoorvervoer', 'Other / not sure yet':'Anders / nog niet zeker', 'Equipment':'Materieel', 'Number of containers':'Aantal containers', 'Cargo and handling notes':'Lading- en behandelingsnotities', 'Support needed':'Benodigde ondersteuning', 'Customs handling':'Douaneafhandeling', 'Door delivery':'Deurlevering', 'Shipment type':'Type zending', 'Cargo ready date':'Lading gereed op', 'Send quote request →':'Offerteaanvraag versturen →',
    'Privacy.':'Privacy.', 'I agree that Sea and Shore may use these details to respond.':'Ik ga ermee akkoord dat Sea and Shore deze gegevens mag gebruiken om te reageren.', 'Planning estimate only. Live rates, space and route details are confirmed by our team.':'Alleen een planningsinschatting. Actuele tarieven, ruimte en routedetails worden door ons team bevestigd.',
    'International freight coordination, customs support and warehousing from Rotterdam — connected worldwide.':'Internationale vrachtcoördinatie, douaneondersteuning en opslag vanuit Rotterdam — wereldwijd verbonden.', 'Available 24/7':'24/7 bereikbaar'
    ,'Every part of the':'Elk onderdeel van de', 'shipment,':'zending,', 'handled.':'verzorgd.', 'Freight forwarding':'Expeditie', 'Customs &':'Douane &', 'documents':'documenten', 'The parts that':'De onderdelen die', 'sit around the freight.':'rond het transport liggen.', 'Support services':'Ondersteunende diensten', 'Cargo insurance':'Transportverzekering', 'Track and trace':'Track & trace', 'Online container booking':'Online containerboeking', '24/7 operations line':'Operationslijn 24/7', 'Cargo we handle':'Lading die wij behandelen', 'Familiar with what':'Bekend met wat', 'you are shipping.':'u vervoert.', 'When to call us':'Wanneer u ons belt', 'The moments where':'De momenten waarop', 'a call saves money.':'een telefoontje geld bespaart.', 'How we work':'Hoe wij werken', 'Four steps, one':'Vier stappen, één', 'line of contact.':'aanspreekpunt.', 'Tell us the route':'Vertel ons de route', 'We quote':'Wij offreren', 'We book and document':'Wij boeken en documenteren', 'We move and report':'Wij vervoeren en rapporteren', 'Why Sea and Shore':'Waarom Sea and Shore', 'Ready when you are':'Klaar wanneer u dat bent', 'Tell us the route and the date you need to hit.':'Vertel ons de route en de datum die u moet halen.'
    ,'News':'Nieuws', 'What is moving at Sea and Shore.':'Wat er speelt bij Sea and Shore.', 'Latest briefings':'Laatste updates', 'Company bulletin':'Bedrijfsbulletin', 'The latest news from our team.':'Het laatste nieuws van ons team.', 'Company news':'Bedrijfsnieuws', 'Sea freight market':'Zeevrachtmarkt', 'Recent developments, clearly explained.':'Recente ontwikkelingen, helder uitgelegd.', 'Read full update →':'Lees de volledige update →', 'Back to News →':'Terug naar Nieuws →', 'What it means for clients':'Wat dit betekent voor klanten', 'Our practical advice':'Ons praktische advies', 'What to do now':'Wat u nu kunt doen', 'What to ask before booking':'Wat u vóór het boeken moet vragen', 'Market update':'Marktupdate', 'Start here · 8 min read':'Begin hier · 8 min leestijd', 'Topics':'Onderwerpen', 'Eight questions clients ask us most.':'Acht vragen die klanten ons het vaakst stellen.', 'Read the basics →':'Lees de basis →', 'Terms':'Voorwaarden', 'Compliance':'Compliance', 'Planning':'Planning', 'Risk':'Risico', 'Practical':'Praktisch', 'Privacy':'Privacy', 'Your information, handled with care.':'Uw gegevens, zorgvuldig behandeld.', 'Privacy statement':'Privacyverklaring', 'Information we receive':'Gegevens die wij ontvangen', 'Why we use it':'Waarom wij ze gebruiken', 'Who may receive it':'Wie ze kan ontvangen', 'How long we keep it':'Hoe lang wij ze bewaren', 'Your choices':'Uw keuzes', 'Cookies and website tools':'Cookies en websitetools'
  },
  de: {
    'Services':'Leistungen', 'Insights':'Wissen', 'News':'News', 'Contact':'Kontakt', 'Request a quote →':'Angebot anfragen →', 'Request a quote':'Angebot anfragen', 'Quote':'Angebot', 'Home':'Startseite',
    'Plan your shipment →':'Sendung planen →', 'Talk to the team →':'Team kontaktieren →', 'Explore':'Entdecken', 'Partners':'Partner', 'Privacy statement':'Datenschutzerklärung', 'Privacy & cookies':'Datenschutz & Cookies',
    'Sea freight update':'Seefracht-Update', 'All news →':'Alle News →', 'International container news':'Internationale Container-News',
    'Rotterdam · Global reach · 24/7':'Rotterdam · Weltweit vernetzt · 24/7', 'One partner. Every step.':'Ein Partner. Jeder Schritt.', 'What we do':'Unsere Leistungen', 'The Sea and Shore way':'Die Sea-and-Shore-Methode',
    'Sea freight':'Seefracht', 'Air, road & rail':'Luft, Straße & Schiene', 'Special cargo':'Spezialladung', 'Customs clearance':'Zollabfertigung', 'Documentation':'Dokumentation', 'Warehousing':'Lagerung',
    'Answers before you need them.':'Antworten, bevor Sie sie brauchen.', 'Basics':'Grundlagen', 'Volume':'Volumen', 'Cost':'Kosten', 'Read →':'Lesen →', 'Open the knowledge area →':'Wissensbereich öffnen →',
    'Regular contact':'Allgemeiner Kontakt', 'Urgent service':'Dringende Hilfe', 'Our Rotterdam office':'Unser Büro in Rotterdam', 'Available 24/7':'24/7 erreichbar', 'Company video':'Unternehmensvideo', 'See how we work.':'So arbeiten wir.',
    'Quote planner':'Angebotsplaner', 'Shipment details':'Sendungsdetails', 'Planning estimate':'Planungsschätzung', 'Send quote request →':'Angebotsanfrage senden →',
    'Instant route planner':'Direkter Routenplaner', 'Plan your route.':'Route planen.', 'From':'Von', 'To':'Nach', 'Container':'Container', 'Work email':'Geschäftliche E-Mail', 'Name':'Name', 'Email this estimate →':'Schätzung senden →',
    'Your shipment plan':'Ihr Sendungsplan', 'Ocean transit':'Seetransitzeit', 'Port-to-port estimate':'Hafen-zu-Hafen-Schätzung', 'Select a port':'Hafen auswählen', 'Select two different ports for a planning estimate.':'Wählen Sie zwei verschiedene Häfen für eine Planungsschätzung.',
    'FCL':'FCL', 'Latest developments from Sea and Shore.':'Aktuelle Entwicklungen bei Sea and Shore.', 'Knowledge for clearer decisions.':'Wissen für klare Entscheidungen.',
    'Supply chain, made clear.':'Lieferkette, klar gemacht.', 'Based in Rotterdam':'In Rotterdam ansässig', 'Connected worldwide':'Weltweit vernetzt',
    'International logistics works best when one team owns the whole picture.':'Internationale Logistik funktioniert am besten, wenn ein Team den gesamten Überblick behält.',
    'Sea and Shore combines freight forwarding, customs and warehousing into one dependable operation.':'Sea and Shore verbindet Spedition, Zoll und Lagerung zu einem verlässlichen Ablauf.',
    'From Rotterdam, we work with trusted partners in more than 120 countries and keep you informed from booking to final delivery.':'Von Rotterdam aus arbeiten wir mit zuverlässigen Partnern in mehr als 120 Ländern und halten Sie von der Buchung bis zur Endlieferung auf dem Laufenden.',
    'Control, not complexity':'Kontrolle statt Komplexität', 'A better view of every moving part.':'Ein besserer Überblick über jeden beweglichen Teil.', 'One team connects planning, documentation and transport execution.':'Ein Team verbindet Planung, Dokumentation und Transportabwicklung.', 'Reliable handovers.':'Zuverlässige Übergaben.', 'Fast action':'Schnelles Handeln', 'Urgent question? We are available 24/7.':'Dringende Frage? Wir sind 24/7 erreichbar.', 'Contact operations →':'Operations kontaktieren →',
    'Customs support that keeps cargo moving.':'Zollunterstützung, die Ihre Ware in Bewegung hält.', 'Practical expertise for imports, documents and compliance.':'Praktische Expertise für Importe, Dokumente und Compliance.',
    'Logistics that moves business.':'Logistik, die Unternehmen voranbringt.', 'Start with the service you need.':'Beginnen Sie mit der Leistung, die Sie benötigen.', 'We coordinate the connected steps, so your team keeps one clear line of communication.':'Wir koordinieren die verbundenen Schritte, damit Ihr Team eine klare Kommunikationslinie behält.',
    'FCL and LCL on the main trade lanes, with space confirmed before the cut-off.':'FCL und LCL auf den wichtigsten Handelsrouten, mit bestätigtem Platz vor dem Cut-off.', 'Explore sea freight →':'Seefracht entdecken →', 'Faster routings for when the sailing schedule no longer fits the deadline.':'Schnellere Routen, wenn der Fahrplan die Frist nicht mehr einhält.', 'Explore transport modes →':'Transportarten entdecken →',
    'Out-of-gauge, reefer and dangerous goods, planned around permits and equipment.':'Übermaß-, Kühl- und Gefahrgut, geplant nach Genehmigungen und Equipment.', 'Explore special cargo →':'Spezialladung entdecken →', 'AEO-certified import, export and transit entries, checked before submission.':'AEO-zertifizierte Import-, Export- und Transitabfertigungen, vor der Einreichung geprüft.', 'Explore customs support →':'Zollunterstützung entdecken →',
    'Bills of lading, origin certificates and credit document sets, checked against the booking.':'Konnossemente, Ursprungszeugnisse und Akkreditivdokumente, gegen die Buchung geprüft.', 'Explore documentation →':'Dokumentation entdecken →', 'Bonded and standard storage near the port, connected to the same booking.':'Zolllager und reguläre Lagerung nahe dem Hafen, verbunden mit derselben Buchung.', 'Explore warehousing →':'Lagerung entdecken →', 'See all services, including insurance and tracking →':'Alle Leistungen einschließlich Versicherung und Tracking ansehen →',
    'A practical knowledge area for importers, written by the people who handle the shipments.':'Ein praktischer Wissensbereich für Importeure, geschrieben von den Menschen, die Sendungen abwickeln.', 'How a container shipment actually runs.':'Wie eine Containersendung tatsächlich abläuft.', 'The sequence from booking to delivery, and which container fits which cargo.':'Der Ablauf von der Buchung bis zur Lieferung und welcher Container zu welcher Ware passt.', 'FCL or LCL: which one fits your cargo.':'FCL oder LCL: Was passt zu Ihrer Ware?', 'Where the tipping point sits, and what changes at the destination when you share a box.':'Wo der Wendepunkt liegt und was sich am Ziel ändert, wenn Sie einen Container teilen.', 'What actually drives your freight rate.':'Was Ihre Frachtrate tatsächlich bestimmt.', 'Why the lowest quote is often not the lowest cost, and which charges arrive later.':'Warum das niedrigste Angebot oft nicht die niedrigsten Kosten bedeutet und welche Kosten später anfallen.',
    'Personal service, backed by a global network.':'Persönlicher Service, gestützt durch ein globales Netzwerk.', 'countries reached through trusted local partners':'Länder über zuverlässige lokale Partner erreicht', 'availability for urgent logistics questions':'Erreichbarkeit für dringende Logistikfragen', 'certified, with fast-track import support':'zertifiziert, mit beschleunigter Importunterstützung', 'point of contact across your logistics process':'Ansprechpartner für Ihren gesamten Logistikprozess',
    'Choose a topic':'Thema wählen', 'New quote or shipment':'Neues Angebot oder neue Sendung', 'Existing shipment or booking':'Bestehende Sendung oder Buchung', 'Customs or documentation':'Zoll oder Dokumentation', 'Warehousing or distribution':'Lagerung oder Distribution', 'Partnership or general question':'Partnerschaft oder allgemeine Frage', 'Other':'Sonstiges', 'Send a message':'Nachricht senden', 'Tell us what you need. We will route it to the right team.':'Sagen Sie uns, was Sie benötigen. Wir leiten Ihre Anfrage an das richtige Team weiter.', 'Company':'Unternehmen', 'Phone':'Telefon', 'What do you need help with?':'Wobei können wir helfen?', 'How can we help?':'Wie können wir helfen?', 'Send message →':'Nachricht senden →',
    'Full container load (FCL)':'Volle Containerladung (FCL)', 'Less than container load (LCL)':'Teilladung (LCL)', 'Air freight':'Luftfracht', 'Road or rail freight':'Straßen- oder Schienenfracht', 'Other / not sure yet':'Sonstiges / noch nicht sicher', 'Equipment':'Equipment', 'Number of containers':'Anzahl Container', 'Cargo and handling notes':'Fracht- und Abwicklungshinweise', 'Support needed':'Benötigte Unterstützung', 'Customs handling':'Zollabfertigung', 'Door delivery':'Türzustellung', 'Shipment type':'Sendungsart', 'Cargo ready date':'Ware bereit ab', 'Send quote request →':'Angebotsanfrage senden →',
    'Privacy.':'Datenschutz.', 'I agree that Sea and Shore may use these details to respond.':'Ich stimme zu, dass Sea and Shore diese Angaben zur Beantwortung verwenden darf.', 'Planning estimate only. Live rates, space and route details are confirmed by our team.':'Nur eine Planungsschätzung. Aktuelle Raten, Kapazitäten und Routendetails werden von unserem Team bestätigt.',
    'International freight coordination, customs support and warehousing from Rotterdam — connected worldwide.':'Internationale Frachtkoordination, Zollunterstützung und Lagerung aus Rotterdam — weltweit vernetzt.', 'Available 24/7':'24/7 erreichbar'
    ,'Every part of the':'Jeder Teil der', 'shipment,':'Sendung,', 'handled.':'betreut.', 'Freight forwarding':'Spedition', 'Customs &':'Zoll &', 'documents':'Dokumente', 'The parts that':'Die Teile, die', 'sit around the freight.':'die Fracht ergänzen.', 'Support services':'Unterstützende Leistungen', 'Cargo insurance':'Transportversicherung', 'Track and trace':'Sendungsverfolgung', 'Online container booking':'Online-Containerbuchung', '24/7 operations line':'Operations-Hotline 24/7', 'Cargo we handle':'Fracht, die wir abwickeln', 'Familiar with what':'Vertraut mit dem, was', 'you are shipping.':'Sie versenden.', 'When to call us':'Wann Sie uns anrufen sollten', 'The moments where':'Die Momente, in denen', 'a call saves money.':'ein Anruf Geld spart.', 'How we work':'So arbeiten wir', 'Four steps, one':'Vier Schritte, ein', 'line of contact.':'Ansprechpartner.', 'Tell us the route':'Nennen Sie uns die Route', 'We quote':'Wir kalkulieren', 'We book and document':'Wir buchen und dokumentieren', 'We move and report':'Wir bewegen und informieren', 'Why Sea and Shore':'Warum Sea and Shore', 'Ready when you are':'Bereit, wenn Sie es sind', 'Tell us the route and the date you need to hit.':'Nennen Sie uns die Route und den Termin, den Sie einhalten müssen.'
    ,'News':'News', 'What is moving at Sea and Shore.':'Was sich bei Sea and Shore bewegt.', 'Latest briefings':'Aktuelle Meldungen', 'Company bulletin':'Unternehmensbulletin', 'The latest news from our team.':'Die neuesten Nachrichten aus unserem Team.', 'Company news':'Unternehmensnachrichten', 'Sea freight market':'Seefrachtmarkt', 'Recent developments, clearly explained.':'Aktuelle Entwicklungen, klar erklärt.', 'Read full update →':'Vollständiges Update lesen →', 'Back to News →':'Zurück zu News →', 'What it means for clients':'Was das für Kunden bedeutet', 'Our practical advice':'Unser praktischer Rat', 'What to do now':'Was jetzt zu tun ist', 'What to ask before booking':'Was Sie vor der Buchung fragen sollten', 'Market update':'Marktupdate', 'Start here · 8 min read':'Hier beginnen · 8 Min. Lesezeit', 'Topics':'Themen', 'Eight questions clients ask us most.':'Acht Fragen, die Kunden uns am häufigsten stellen.', 'Read the basics →':'Grundlagen lesen →', 'Terms':'Bedingungen', 'Compliance':'Compliance', 'Planning':'Planung', 'Risk':'Risiko', 'Practical':'Praktisch', 'Privacy':'Datenschutz', 'Your information, handled with care.':'Ihre Daten, sorgfältig behandelt.', 'Privacy statement':'Datenschutzerklärung', 'Information we receive':'Informationen, die wir erhalten', 'Why we use it':'Warum wir sie verwenden', 'Who may receive it':'Wer sie erhalten kann', 'How long we keep it':'Wie lange wir sie aufbewahren', 'Your choices':'Ihre Wahlmöglichkeiten', 'Cookies and website tools':'Cookies und Website-Tools'
  }
};

const pageCopy = {
  index: {
    nl: { hero: 'Logistiek,<br><em>helder</em> geregeld.', intro: 'Wij coördineren internationaal transport, documentatie en douane zodat uw lading op de juiste plek komt — zonder onnodige complexiteit.', logistics: 'Logistiek die<br>uw bedrijf vooruitbrengt.', proof: 'Persoonlijke service, gedragen door een wereldwijd netwerk.' },
    de: { hero: 'Lieferkette,<br><em>klar</em> geregelt.', intro: 'Wir koordinieren internationale Fracht, Dokumentation und Zoll, damit Ihre Ware ankommt — ohne unnötige Komplexität.', logistics: 'Logistik, die<br>Ihr Unternehmen voranbringt.', proof: 'Persönlicher Service, gestützt durch ein globales Netzwerk.' }
  },
  services: {
    nl: { title: 'Logistiek die<br>vooruitgang mogelijk maakt.', lead: 'Van een enkele container tot een complexe internationale supply chain: één team houdt overzicht, tempo en communicatie helder.' },
    de: { title: 'Logistik, die<br>Fortschritt möglich macht.', lead: 'Vom einzelnen Container bis zur komplexen internationalen Lieferkette: Ein Team sorgt für Übersicht, Tempo und klare Kommunikation.' }
  },
  insights: {
    nl: { title: 'Kennis die<br>uw zending vooruithelpt.', lead: 'Praktische uitleg over zeevracht, documentatie, douane en kosten — geschreven door de mensen die de zendingen behandelen.' },
    de: { title: 'Wissen, das<br>Ihre Sendung weiterbringt.', lead: 'Praktische Informationen zu Seefracht, Dokumentation, Zoll und Kosten — von den Menschen, die Ihre Sendungen betreuen.' }
  },
  news: {
    nl: { title: 'Nieuws uit<br>onze wereld.', lead: 'Ontwikkelingen bij Sea and Shore en de routes, havens en markten die uw logistiek beïnvloeden.' },
    de: { title: 'Neuigkeiten aus<br>unserer Welt.', lead: 'Entwicklungen bei Sea and Shore sowie zu Routen, Häfen und Märkten, die Ihre Logistik beeinflussen.' }
  },
  contact: {
    nl: { title: 'Spreek met een<br>logistiek specialist.', lead: 'Voor een offerte, een urgente verzendvraag of een praktisch gesprek over uw supply chain: neem direct contact op met ons team.' },
    de: { title: 'Sprechen Sie mit einem<br>Logistikspezialisten.', lead: 'Für ein Angebot, eine dringende Versandfrage oder ein praktisches Gespräch über Ihre Lieferkette: Kontaktieren Sie unser Team direkt.' }
  },
  quote: {
    nl: { title: 'Geef uw zending<br>een helder vertrekpunt.', lead: 'Maak een planningsinschatting voor een volle container en stuur uw gegevens naar ons team voor een actuele offerte.' },
    de: { title: 'Geben Sie Ihrer Sendung<br>einen klaren Startpunkt.', lead: 'Erstellen Sie eine Planungsschätzung für eine volle Containerladung und senden Sie die Details für ein aktuelles Angebot an unser Team.' }
  }
};

const langNames = { en: 'EN', nl: 'NL', de: 'DE' };
const titles = {
  nl: { index: 'Sea and Shore Services — Logistiek, helder geregeld.', services: 'Diensten — Sea and Shore Services', insights: 'Kennisbank — Sea and Shore Services', news: 'Nieuws — Sea and Shore Services', contact: 'Contact — Sea and Shore Services', quote: 'Offerte aanvragen — Sea and Shore Services', privacy: 'Privacyverklaring — Sea and Shore Services' },
  de: { index: 'Sea and Shore Services — Lieferkette, klar gemacht.', services: 'Leistungen — Sea and Shore Services', insights: 'Wissen — Sea and Shore Services', news: 'News — Sea and Shore Services', contact: 'Kontakt — Sea and Shore Services', quote: 'Angebot anfragen — Sea and Shore Services', privacy: 'Datenschutzerklärung — Sea and Shore Services' }
};
const page = location.pathname.split('/').pop()?.replace('.html', '') || 'index';
const requested = new URLSearchParams(location.search).get('lang');
let language = ['en', 'nl', 'de'].includes(requested) ? requested : localStorage.getItem('sea-and-shore-language') || 'en';

function replaceTextNodes(dictionary) {
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, { acceptNode(node) {
    return node.parentElement && !['SCRIPT', 'STYLE'].includes(node.parentElement.tagName) ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_REJECT;
  }});
  const nodes = []; while (walker.nextNode()) nodes.push(walker.currentNode);
  nodes.forEach(node => { const key = node.nodeValue.trim(); if (dictionary[key]) node.nodeValue = node.nodeValue.replace(key, dictionary[key]); });
}

function translateAttributes(dictionary) {
  document.querySelectorAll('[placeholder], [aria-label], [title]').forEach(element => {
    ['placeholder', 'aria-label', 'title'].forEach(attribute => {
      const value = element.getAttribute(attribute);
      if (value && dictionary[value]) element.setAttribute(attribute, dictionary[value]);
    });
  });
  const description = document.querySelector('meta[name="description"]');
  if (description && dictionary[description.content]) description.content = dictionary[description.content];
}

function applyPageCopy(copy) {
  if (!copy) return;
  const hero = document.querySelector('.hero-copy h1, .page-hero h1');
  const intro = document.querySelector('.hero-copy > p, .page-hero p');
  if (hero && copy.title || hero && copy.hero) hero.innerHTML = copy.title || copy.hero;
  if (intro && copy.lead || intro && copy.intro) intro.textContent = copy.lead || copy.intro;
  if (page === 'index') {
    const heading = document.querySelector('.section-head h2'); if (heading && copy.logistics) heading.innerHTML = copy.logistics;
    const proof = document.querySelector('.proof-copy h2'); if (proof && copy.proof) proof.textContent = copy.proof;
  }
}

const localizedArticles = {
  nl: {
    'news-peak-season-congestion': ['Piekseizoen houdt druk op Aziatische havens hoog.', 'Sterke exportvraag en weersverstoring zetten vaarschema’s en terminaldoorstroming onder druk. Het effect merkt u meestal bij de volgende overdracht, niet alleen in de gepubliceerde ETA.', 'Wat dit betekent voor klanten', 'Een vertraging van een schip is zelden alleen een vertraging van een schip. Bij congestie stapelen containers zich op: lege apparatuur komt later, cut-offs worden strakker en inlandse capaciteit kan schaars worden.', 'Plan rond de overdrachten', 'Werk vanaf de gewenste leverweek terug en neem ruimte op voor gate-in, eventuele overslag en eindafhaling. Maak onderscheid tussen de door de rederij geschatte aankomst en de dag waarop uw magazijn werkelijk kan ontvangen.', 'Wat u nu kunt doen', 'Bevestig de cargo-ready datum vroeg, stuur documenten vóór de cut-off en reserveer inlandse levering zodra lossing waarschijnlijk is. Vraag bij een vaste leverdatum om de volgende twee afvaarten te controleren.'],
    'news-asia-us-rates': ['Containertarieven kunnen in dezelfde week verschillend bewegen.', 'Berichten uit de markt laten gemengde tariefbewegingen zien op de Azië–VS-route. Congestie en aanhoudende vraag blijven echter druk zetten op het netwerk.', 'Wat dit betekent voor klanten', 'De vraag is niet alleen of een tarief in het algemeen stijgt of daalt. De relevante vraag is of ruimte, apparatuur, routing en kosten op bestemming beschikbaar zijn voor uw specifieke zending.', 'Vergelijk de zending, niet alleen het getal', 'Twee tarieven kunnen vergelijkbaar lijken, maar verschillende voorwaarden bevatten: een directe dienst tegenover meerdere overslagen, meer vrije tijd op bestemming of lokale afhandeling buiten de offerte.', 'Ons praktische advies', 'Vraag naar de volledige kosten en routing, inclusief kosten op bestemming en vrije tijd. Als de datum belangrijk is, kies dan voor een bevestigde afvaart en een realistisch inlandplan boven het laagste startbedrag.'],
    'news-red-sea-services': ['Routing via de Rode Zee keert slechts geleidelijk terug.', 'Een deel van de capaciteit tussen Azië en Europa keert terug via de Rode Zee, maar de diensten blijven gemengd. Voor importeurs telt de route op de offerte meer dan een algemene uitspraak dat transittijden weer normaal zijn.', 'Wat dit betekent voor klanten', 'Een route via Kaap de Goede Hoop en via Suez verschillen niet alleen in transittijd. Ze beïnvloeden de rotatie van apparatuur, betrouwbaarheid van het schema, verbindingen in overslaghavens en beschikbare ruimte.', 'Controleer de daadwerkelijke dienst', 'Vraag bij urgente lading welke havenparen, schepen en overslagen achter de offerte zitten. Dat antwoord kan per afvaart veranderen. Pas oude transit-aannames aan voordat de goederen gereed zijn.', 'Wat u vóór het boeken moet vragen', 'Vraag naar de geplande route, het aantal overslagen, de verwachte loshaven, vrije tijd en het eerstvolgende alternatief. Wij kunnen de opties naast elkaar zetten en uitleggen wat dit betekent voor uw cargo-ready datum en leverdoel.']
  },
  de: {
    'news-peak-season-congestion': ['Die Hochsaison hält den Druck auf asiatische Häfen hoch.', 'Starke Exportnachfrage und wetterbedingte Störungen setzen Fahrpläne und Terminalabläufe unter Druck. Die operative Wirkung zeigt sich meist bei der nächsten Übergabe, nicht nur in der veröffentlichten ETA.', 'Was das für Kunden bedeutet', 'Eine Schiffsverspätung ist selten nur eine Schiffsverspätung. Bei Stauungen bündeln sich Container: leeres Equipment kommt später, Cut-offs werden enger und Inlandskapazitäten können knapp werden.', 'Um die Übergaben herum planen', 'Planen Sie von der gewünschten Lieferwoche rückwärts und berücksichtigen Sie Puffer für Gate-in, Umschlag und Endabholung. Unterscheiden Sie zwischen der geschätzten Ankunft der Reederei und dem Tag, an dem Ihr Lager tatsächlich empfangen kann.', 'Was jetzt zu tun ist', 'Bestätigen Sie das Cargo-ready-Datum früh, senden Sie Dokumente vor dem Cut-off und reservieren Sie Inlandslieferung, sobald die Entladung absehbar ist. Bei einem festen Termin prüfen wir die nächsten zwei Abfahrten.'],
    'news-asia-us-rates': ['Containerraten können sich in derselben Woche unterschiedlich entwickeln.', 'Marktberichte zeigen gemischte Ratenbewegungen im Handel Asien–USA. Stauungen und anhaltende Nachfrage setzen das Netzwerk jedoch weiterhin unter Druck.', 'Was das für Kunden bedeutet', 'Die Frage ist nicht nur, ob eine Rate allgemein steigt oder fällt. Entscheidend ist, ob Kapazität, Equipment, Routing und Kosten am Ziel für Ihre konkrete Sendung verfügbar sind.', 'Die Sendung vergleichen, nicht nur die Zahl', 'Zwei Raten können vergleichbar aussehen, aber unterschiedliche Bedingungen enthalten: Direktdienst statt mehrerer Umschläge, längere freie Zeit am Ziel oder lokale Abwicklung außerhalb des Angebots.', 'Unser praktischer Rat', 'Fragen Sie nach den Gesamtkosten und dem Routing einschließlich Zielkosten und freier Zeit. Wenn der Termin zählt, priorisieren Sie eine bestätigte Abfahrt und einen realistischen Inlandplan vor dem niedrigsten Anfangspreis.'],
    'news-red-sea-services': ['Die Routenführung durch das Rote Meer kehrt nur schrittweise zurück.', 'Ein Teil der Kapazität zwischen Asien und Europa kehrt durch das Rote Meer zurück, die Dienste bleiben jedoch gemischt. Für Importeure ist die Route im Angebot wichtiger als die allgemeine Aussage, Transitzeiten seien wieder normal.', 'Was das für Kunden bedeutet', 'Eine Kap-Route und eine Suez-Route unterscheiden sich nicht nur in der Transitzeit. Sie beeinflussen Equipment-Rotation, Zuverlässigkeit, Verbindungen in Umschlaghäfen und freie Kapazitäten.', 'Den tatsächlichen Dienst prüfen', 'Fragen Sie bei dringender Fracht, welche Hafenpaare, Schiffe und Umschläge hinter dem Angebot stehen. Die Antwort kann sich von Abfahrt zu Abfahrt ändern. Passen Sie alte Transitannahmen an, bevor die Ware bereit ist.', 'Was Sie vor der Buchung fragen sollten', 'Fragen Sie nach geplanter Route, Anzahl der Umschläge, erwartetem Löschhafen, freier Zeit und der nächsten verfügbaren Alternative. Wir stellen die Optionen gegenüber und erklären die Folgen für Ihr Cargo-ready-Datum und Lieferziel.']
  }
};

function localizeArticle() {
  const content = localizedArticles[language]?.[page];
  if (!content) return;
  const [title, lead, aside, intro, heading, body, finalHeading, finalBody] = content;
  const article = document.querySelector('.news-article');
  if (!article) return;
  article.querySelector('h1').textContent = title;
  article.querySelector('.news-article-head p').textContent = lead;
  article.querySelector('.news-aside').innerHTML = aside.replace(' ', '<br>');
  const bodyNode = article.querySelector('.news-body');
  const source = bodyNode.querySelector('.source-note');
  const actions = bodyNode.querySelector('.article-actions');
  const sourceLink = source.querySelector('a');
  source.textContent = language === 'nl' ? 'Bron: externe marktberichtgeving. ' : 'Quelle: externe Marktberichterstattung. ';
  sourceLink.textContent = language === 'nl' ? 'Lees het oorspronkelijke bericht ↗' : 'Originalbericht lesen ↗';
  source.append(sourceLink);
  bodyNode.replaceChildren(Object.assign(document.createElement('p'), { className: 'intro-line', textContent: intro }), Object.assign(document.createElement('h2'), { textContent: heading }), Object.assign(document.createElement('p'), { textContent: body }), source, Object.assign(document.createElement('h2'), { textContent: finalHeading }), Object.assign(document.createElement('p'), { textContent: finalBody }), actions);
}

function localizeLongPages() {
  if (!['services', 'insights', 'news', 'privacy'].includes(page)) return;
  const main = document.querySelector('main');
  if (!main) return;
  const isNl = language === 'nl';
  if (page === 'privacy') {
    const text = isNl ? { title: 'Uw gegevens,<br>zorgvuldig behandeld.', intro: 'Wij gebruiken de informatie die u verstrekt om uw logistieke vraag te beantwoorden en de gevraagde dienst te regelen.', items: [['Welke gegevens wij ontvangen', 'Dit kan uw naam, zakelijke contactgegevens, bedrijfsnaam, zendinggegevens en berichten via onze formulieren omvatten.'], ['Waarom wij deze gegevens gebruiken', 'Wij gebruiken ze om uw aanvraag te beantwoorden, een offerte op te stellen, logistieke diensten te coördineren en aan wettelijke verplichtingen te voldoen. Wij verkopen geen persoonsgegevens.'], ['Met wie wij delen', 'Alleen medewerkers en dienstverleners die de informatie nodig hebben om uw aanvraag of zending af te handelen, ontvangen noodzakelijke gegevens.'], ['Uw rechten', 'U kunt vragen om inzage, correctie, verwijdering, beperking of overdracht van uw gegevens, of bezwaar maken waar dat van toepassing is. Neem contact op via info@sea-and-shore.com.']], heading: 'Privacyverklaring' } : { title: 'Ihre Daten,<br>sorgfältig behandelt.', intro: 'Wir verwenden die von Ihnen bereitgestellten Informationen, um Ihre Logistikanfrage zu beantworten und die gewünschte Leistung zu organisieren.', items: [['Welche Daten wir erhalten', 'Dies kann Ihren Namen, geschäftliche Kontaktdaten, Unternehmensnamen, Sendungsdetails und Nachrichten aus unseren Formularen umfassen.'], ['Warum wir diese Daten verwenden', 'Wir verwenden sie, um Ihre Anfrage zu beantworten, ein Angebot zu erstellen, Logistikleistungen zu koordinieren und gesetzlichen Pflichten nachzukommen. Wir verkaufen keine personenbezogenen Daten.'], ['Mit wem wir teilen', 'Nur Mitarbeitende und Dienstleister, die die Informationen für Ihre Anfrage oder Sendung benötigen, erhalten die erforderlichen Daten.'], ['Ihre Rechte', 'Sie können Auskunft, Berichtigung, Löschung, Einschränkung oder Übertragung Ihrer Daten verlangen oder gegebenenfalls widersprechen. Kontaktieren Sie uns über info@sea-and-shore.com.']], heading: 'Datenschutzerklärung' };
    main.innerHTML = `<section class="page-hero"><div class="wrap"><div class="mono">${text.heading}</div><h1>${text.title}</h1><p>${text.intro}</p></div></section><section class="wrap page-main"><div class="cards">${text.items.map(([heading, body]) => `<article class="card"><h3>${heading}</h3><p>${body}</p></article>`).join('')}</div></section>`;
    return;
  }
  if (page === 'news') {
    const text = isNl ? { kicker: 'Nieuws', title: 'Wat er speelt<br>bij Sea and Shore.', lead: 'Bedrijfsontwikkelingen en beknopte marktupdates die helpen bij praktische beslissingen over uw zending.', latest: 'Laatste marktupdates', company: 'Bedrijfsnieuws', companyText: 'Projectmijlpalen, nieuwe routes, samenwerkingen en updates van ons team.', updates: [['Druk op Aziatische havens', 'Congestie en weersverstoring maken vroege planning en ruime buffers belangrijk.'], ['Tarieven en capaciteit', 'Vergelijk route, vrije tijd en kosten op bestemming — niet alleen het laagste tarief.'], ['Routing via de Rode Zee', 'Diensten keren geleidelijk terug; controleer de route per afvaart.']], cta: 'Volg ons op LinkedIn ↗' } : { kicker: 'News', title: 'Was sich bei<br>Sea and Shore bewegt.', lead: 'Unternehmensentwicklungen und kompakte Marktupdates, die praktische Entscheidungen für Ihre Sendung erleichtern.', latest: 'Aktuelle Marktupdates', company: 'Unternehmensnachrichten', companyText: 'Projektmeilensteine, neue Routen, Partnerschaften und Updates aus unserem Team.', updates: [['Druck auf asiatische Häfen', 'Stauungen und Wetterstörungen machen frühe Planung und ausreichende Puffer wichtig.'], ['Raten und Kapazität', 'Vergleichen Sie Route, freie Zeit und Zielkosten — nicht nur die niedrigste Rate.'], ['Routing durch das Rote Meer', 'Dienste kehren schrittweise zurück; prüfen Sie die Route je Abfahrt.']], cta: 'Auf LinkedIn folgen ↗' };
    const links = ['news-peak-season-congestion.html', 'news-asia-us-rates.html', 'news-red-sea-services.html'];
    main.innerHTML = `<section class="page-hero"><div class="wrap"><div class="mono">${text.kicker}</div><h1>${text.title}</h1><p>${text.lead}</p></div></section><section class="wrap news-page"><article class="bulletin"><div class="bulletin-copy"><div class="mono">${text.company}</div><h2>${text.company}</h2><p>${text.companyText}</p><p><a class="button light" href="https://www.linkedin.com/company/sea-and-shore-services-b-v/" target="_blank" rel="noreferrer">${text.cta}</a></p></div></article><div class="section-head"><div><div class="mono">${text.latest}</div><h2>${text.latest}</h2></div></div><div class="news-list">${text.updates.map(([heading, body], index) => `<article><div class="mono">${String(index + 1).padStart(2, '0')}</div><h3>${heading}</h3><p>${body}</p><a href="${links[index]}">${isNl ? 'Lees volledige update →' : 'Vollständiges Update lesen →'}</a></article>`).join('')}</div></section>`;
    return;
  }
  if (page === 'services') {
    const text = isNl ? {
      kicker: 'Diensten', title: 'Elke stap van uw<br>zending, <em>verzorgd.</em>', lead: 'Eén team coördineert transport, douane, documenten en opslag — zodat uw lading blijft bewegen en u altijd weet waar u aan toe bent.',
      freight: 'Transport', freightText: 'Zeevracht, luchtvracht, weg- en spoorvervoer voor FCL, LCL, speciale lading en cross-trade. Wij bevestigen ruimte, plannen de inlandse trajecten en houden één boekingsreferentie aan.',
      customs: 'Douane & documenten', customsText: 'Onze AEO-gecertificeerde specialisten verzorgen import-, export- en transitaangiften, cognossementen, oorsprongsdocumenten en controles van facturen en paklijsten.',
      storage: 'Opslag & distributie', storageText: 'Douane-entrepot en reguliere opslag nabij Rotterdam, inclusief uitladen, palletiseren, orderpicking en verdere distributie in Europa.',
      call: 'Wanneer u ons belt', callText: 'Neem vroeg contact op bij een vaste leverdatum, een douanevraag, afwijkende lading of wanneer u offertes vergelijkt. Dat voorkomt vertragingen en verrassingen op bestemming.', cta: 'Offerte aanvragen →'
    } : {
      kicker: 'Leistungen', title: 'Jeder Schritt Ihrer<br>Sendung, <em>betreut.</em>', lead: 'Ein Team koordiniert Transport, Zoll, Dokumente und Lagerung — damit Ihre Ware in Bewegung bleibt und Sie jederzeit den Überblick haben.',
      freight: 'Transport', freightText: 'See-, Luft-, Straßen- und Schienenfracht für FCL, LCL, Spezialfracht und Cross-Trade. Wir bestätigen Kapazität, planen die Inlandstrecken und führen eine Buchungsreferenz.',
      customs: 'Zoll & Dokumente', customsText: 'Unsere AEO-zertifizierten Spezialisten erledigen Import-, Export- und Transitabfertigungen, Konnossemente, Ursprungsdokumente sowie Rechnungs- und Packlistenprüfungen.',
      storage: 'Lagerung & Distribution', storageText: 'Zolllager und reguläre Lagerung nahe Rotterdam, einschließlich Entladen, Palettieren, Kommissionierung und Weiterverteilung in Europa.',
      call: 'Wann Sie uns kontaktieren sollten', callText: 'Melden Sie sich früh bei einem festen Liefertermin, einer Zollfrage, besonderer Fracht oder beim Angebotsvergleich. Das verhindert Verzögerungen und Überraschungen am Ziel.', cta: 'Angebot anfragen →'
    };
    main.innerHTML = `<section class="page-hero"><div class="wrap"><div class="mono">${text.kicker}</div><h1>${text.title}</h1><p>${text.lead}</p></div></section><section class="wrap page-main"><div class="cards"><article class="card"><div class="mono">01</div><h3>${text.freight}</h3><p>${text.freightText}</p></article><article class="card"><div class="mono">02</div><h3>${text.customs}</h3><p>${text.customsText}</p></article><article class="card"><div class="mono">03</div><h3>${text.storage}</h3><p>${text.storageText}</p></article></div><section class="cta"><div class="wrap cta-grid"><div><div class="mono">${text.call}</div><p>${text.callText}</p></div><div><a class="button" href="quote.html">${text.cta}</a></div></div></section></section>`;
  } else {
    const text = isNl ? {
      kicker: 'Kennisbank', title: 'Wat elke importeur<br>moet weten.', lead: 'Heldere uitleg over containervervoer, douane, documenten, planning en kosten — geschreven voor betere beslissingen vóór u boekt.',
      topics: [['Containerzending van begin tot eind', 'Boeking, cut-offs, afvaart, aankomst, aangifte, vrijgave en terugbrengen van de lege container.'], ['FCL of LCL', 'Wanneer een eigen container of deellading past bij volume, gewicht, tijd en risico.'], ['Incoterms', 'Wie betaalt, wie het risico draagt en waarom de juiste afspraak op de offerte moet staan.'], ['Douane & documenten', 'De documenten die douane verwacht en hoe u vertraging voorkomt.'], ['Planning & kosten', 'Transit, vrije tijd, havenkosten en de details die een laag tarief alsnog duur maken.'], ['Verstoring op de route', 'Hoe congestie, omleidingen en rollovers uw leverdatum beïnvloeden.']], cta: 'Bespreek uw route →'
    } : {
      kicker: 'Wissen', title: 'Was jeder Importeur<br>wissen sollte.', lead: 'Klare Erklärungen zu Containertransport, Zoll, Dokumenten, Planung und Kosten — für bessere Entscheidungen vor der Buchung.',
      topics: [['Containersendung von Anfang bis Ende', 'Buchung, Cut-offs, Abfahrt, Ankunft, Anmeldung, Freigabe und Rückgabe des leeren Containers.'], ['FCL oder LCL', 'Wann ein eigener Container oder Teilladung zu Volumen, Gewicht, Zeit und Risiko passt.'], ['Incoterms', 'Wer zahlt, wer das Risiko trägt und warum die richtige Vereinbarung im Angebot stehen muss.'], ['Zoll & Dokumente', 'Die Unterlagen, die der Zoll erwartet, und wie Sie Verzögerungen vermeiden.'], ['Planung & Kosten', 'Transit, freie Zeit, Hafenkosten und Details, die eine niedrige Rate trotzdem teuer machen.'], ['Störungen auf der Route', 'Wie Stauungen, Umleitungen und Rollovers Ihren Liefertermin beeinflussen.']], cta: 'Route besprechen →'
    };
    main.innerHTML = `<section class="page-hero"><div class="wrap"><div class="mono">${text.kicker}</div><h1>${text.title}</h1><p>${text.lead}</p></div></section><section class="wrap page-main"><div class="cards">${text.topics.map(([heading, body], index) => `<article class="card"><div class="mono">0${index + 1}</div><h3>${heading}</h3><p>${body}</p></article>`).join('')}</div><section class="cta"><div class="wrap cta-grid"><div><div class="mono">Sea and Shore</div><p>${isNl ? 'Heeft u een vraag over een specifieke zending? Ons team legt uit welke gegevens en keuzes voor uw route relevant zijn.' : 'Haben Sie eine Frage zu einer bestimmten Sendung? Unser Team erklärt, welche Angaben und Entscheidungen für Ihre Route wichtig sind.'}</p></div><div><a class="button" href="contact.html">${text.cta}</a></div></div></section></section>`;
  }
}

function addSwitcher() {
  document.querySelectorAll('.site-header').forEach(header => {
    if (header.querySelector('.language-switch')) return;
    const wrap = document.createElement('nav'); wrap.className = 'language-switch'; wrap.setAttribute('aria-label', 'Website language');
    wrap.innerHTML = Object.entries(langNames).map(([code, name]) => `<a href="?lang=${code}" data-language="${code}"${code === language ? ' aria-current="page"' : ''}>${name}</a>`).join('');
    wrap.querySelectorAll('[data-language]').forEach(link => link.addEventListener('click', () => localStorage.setItem('sea-and-shore-language', link.dataset.language)));
    header.querySelector('.nav')?.after(wrap);
  });
}

function translate() {
  document.documentElement.lang = language;
  addSwitcher();
  if (language === 'en') return;
  const dictionary = translations[language];
  replaceTextNodes(dictionary);
  translateAttributes(dictionary);
  applyPageCopy(pageCopy[page]?.[language]);
  localizeArticle();
  localizeLongPages();
  document.title = titles[language]?.[page] || document.title;
}

translate();
